In [ ]:
#NumPY and Pandas Implementation Assignment
#Name :- Disha Goyal
#Roll no :- 2501730433
#Course:BTech cse (ai and ml)
#Section:G

In [4]:
#PART-1 NUMPY
import numpy as np

In [46]:
#np.array()

#Description: creates a n-dimensional array from python sequences

#1 1-D array from a list
arr1 = np.array([1,2,3,4,5])
print(arr1)

#2 2-D array from a list 
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

#3 1-D array from a Tuple
arr3 = np.array((5, 10, 15, 20))
print(arr3)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[ 5 10 15 20]

In [47]:
#np.zeros()

#1 creating a 1D array of 5 zeroes
arr1 = np.zeros(5)
print(arr1)

#2  creating a 2D array of 2 rows 3 columns of zeroes
arr2 = np.zeros((2, 3))
print(arr2)

#3  creating a 3D array of 2 matrices,2rows,2columns of zeroes 
arr3 = np.zeros((2, 2, 3))
print(arr3)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]

In [8]:
#np.ones()
# 1. Creating a 1D array of 5 ones (float by default)
arr1 = np.ones(5)

# 2. Creating a 2D array (2 rows, 3 columns) of ones
arr2 = np.ones((2, 3))

# 3. Creating a 2D integer array (3 rows, 2 columns) of ones
arr3 = np.ones((3, 2), dtype=int)

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1 1]
 [1 1]
 [1 1]]

In [23]:
arr=np.array([[12,3,6],[4,335,64]])
print(arr.size) #total size
print(arr.ndim)#check dimension

6
2

In [49]:
#sum operations
arr=np.array([[12,3,6],[4,335,64]])
#1 give sum of whole array
print(arr.sum())
#2 add vertically (column wise)
print(arr.sum(axis=0))
#3 add horizontally (row wise)
print(arr.sum(axis=1))

424
[ 16 338  70]
[ 21 403]

In [50]:
#reshape operations
arr = np.array([[12, 3, 6], [4, 335, 64]])

# 1. Reshape automatically specifying rows using -1
reshape1 = arr.reshape(-1, 3)

# 2. Reshape into a 3D array (depth=1, rows=2, cols=3)
reshape2 = arr.reshape(1, 2, 3)

# 3. Reshape into a 1D vector (6 elements)
reshape3 = arr.reshape(6)

In [60]:
#ravel operation
# 1. converting 2D array into 1D array
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1.ravel())


# 2.chnaging value(original array change ho jata hai)
arr2 = np.array([[12, 3, 6], [4, 335, 64]])
demo = arr2.ravel()
demo[0] = 100  # changes first element
print(arr2)

# 3. converting 3D into 1D
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr3.ravel())

[1 2 3 4 5 6]
[[100   3   6]
 [  4 335  64]]
[1 2 3 4 5 6 7 8]

In [32]:
arr=np.array([12,3,6,3,56,78,4,335,64,65,78,97])
#eye= gives identity matrix
k=arr.reshape(3,4)
arr[0]=100
k
#change in original array

array([[100,   3,   6,   3],
       [ 56,  78,   4, 335],
       [ 64,  65,  78,  97]])

In [57]:
#copy operation
arr = np.array([12, 3, 6, 3, 56, 78, 4, 335, 64, 65, 78, 97])
k = arr.reshape(3, 4).copy()
arr[0] = 100  # will not change copy array
print(k)

[[ 12   3   6   3]
 [ 56  78   4 335]
 [ 64  65  78  97]]

In [36]:
#broadcasting
d = np.array([100, 56, 87, 56, 65, 78, 89, 76, 98, 45, 57, 87])
print(d % 10)  # numpy array modulo operation
print(d * 2)  # multiply each element by 2
print(d + 10)  # add 10 to each element

[0 6 7 6 5 8 9 6 8 5 7 7]

In [37]:
#normal list
n=[5,6,7]
print(n*3)

[5, 6, 7, 5, 6, 7, 5, 6, 7]

In [40]:
#masking
d=np.array([100,23,45,67,89,98,87,65,43,32,56,78])
mask = (d>80)
print(mask)
print(d[mask]) #will print true values
print(d[~mask]) #approximation symbol prints false values

[ True False False False  True  True  True False False False False False]
[100  89  98  87]
[23 45 67 65 43 32 56 78]

In [41]:
d=np.array([100,23,45,67,89,98,87,65,43,32,56,78])
m=(d>70)&(d<90)
print(d[m])

[89 87 78]

In [56]:
# conditional selection (np.where)
d = np.array([100, 23, 45, 67, 89, 98, 87, 65, 43, 32, 56, 78])

# 1. Return index of the element which satisfies condition (greater than 70)
print(np.where(d > 70))  # return index of elements > 70

# 2. Return index of the element which is even number
print(np.where(d % 2 == 0))  # return index of even elements

# 3. Return index of the element which is less than or equal to 50
print(np.where(d <= 50))  # return index of elements <= 50

(array([ 0,  4,  5,  6, 11]),)
(array([ 0,  5,  9, 10, 11]),)
(array([1, 2, 8, 9]),)

In [55]:
#multiple conditional mapping i.e np.select()
d = np.array([100, 23, 45, 67, 89, 98, 87, 65, 43, 32, 56, 78])

# categorising elements into small,medium,large
cond1=[((d>=40)&(d<=75)),((d>75)&(d<=100))]
choice1=["Small","Medium"]
res1 = np.select(cond,choice,default="Large")
print(res1)

# categorising on behalf of grades
cond2 = [d>=90, (d>=70) &(d<90)]
choice2 = ["A","B"]
res2 = np.select(cond2, choice2, default="C")
print(res2)

# 3. Complex logical conditions combined with OR (|)
m = (d % 2 == 0) | (d % 5 == 0) | (d % 7 == 0)
res3 = d[~m]  # Selecting elements NOT divisible by 2, 5, or 7
print(res3)

['Medium' 'Large' 'Small' 'Small' 'Medium' 'Medium' 'Medium' 'Small'
 'Small' 'Large' 'Small' 'Medium']
['A' 'C' 'C' 'C' 'B' 'A' 'B' 'C' 'C' 'C' 'C' 'B']
[23 67 89 87 43]

In [58]:
#np.arange()
print(np.arange(10))  # 0 to 9 numbers
print(np.arange(5, 20, 2))  # start, stop, step
print(np.arange(10, 0, -1))  # countdown sequence

[0 1 2 3 4 5 6 7 8 9]
[ 5  7  9 11 13 15 17 19]
[10  9  8  7  6  5  4  3  2  1]

In [59]:
#np.linspace()
print(np.linspace(0, 1, 5))  # 5 linearly spaced elements
print(np.linspace(10, 50, 5))  # 10 to 50 split into 5 parts
print(np.linspace(1, 10, 3))  # 3 elements between 1 and 10

[0.   0.25 0.5  0.75 1.  ]
[10. 20. 30. 40. 50.]
[ 1.   5.5 10. ]

In [ ]:
#np.eye() used for identity matrix
print(np.eye(3))  # 3x3 identity matrix
print(np.eye(2, 4))  # 2x4 rectangular identity matrix
print(np.eye(3, dtype=int))  # integer identity matrix

In [9]:
#PART-2 Pandas
import pandas as pd

In [61]:
#pd.read_csv()
df=pd.read_csv("Iris.csv")
print(df)
print(pd.read_csv("Iris.csv").head(2))

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

            Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 6 columns]
   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa

In [11]:
#df.tail()
print(df.tail())# default last 5 rows
print(df.tail(2))#last 2 rows
print(df.tail(3))#last 1 row

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [12]:
#df.info()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    str
dtypes: float64(4), int64(1), str(1)
memory usage: 7.2 KB

In [13]:
#df.describe()
print(df.describe())

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [14]:
#df.shape
print(df.shape) rows,cols
print(df.shape[0]) total rows
print(df.shape[1]) total columns

(150, 6)

In [15]:
len(df.columns.to_list())

6

In [18]:
df.drop(columns="Id")

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [51]:
import pandas as pd
data = {
 "class": ["A", "B", "C","D", "E", "F"],
 "name": ["Disha", "Tavi", "Chinki","Ananya","Divya","Diya"],
 "city": ["Varanasi", "Lucknow", "Kanpur","Varanasi", "Lucknow", "Kanpur"],
 "Day": ["Monday", "Tuesday", "Wednesday","Monday", "Tuesday", "Wednesday"],
 "Sales": ["60000", "24000", "10000","60000", "24000", "10000"]
}
df = pd.DataFrame(data)
print(df)

  class    name      city        Day  Sales
0     A   Disha  Varanasi     Monday  60000
1     B    Tavi   Lucknow    Tuesday  24000
2     C  Chinki    Kanpur  Wednesday  10000
3     D  Ananya  Varanasi     Monday  60000
4     E   Divya   Lucknow    Tuesday  24000
5     F    Diya    Kanpur  Wednesday  10000